/**
 * cookim
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Message model module.
* @module model/Message
* @version 1.0.0
*/
export default class Message {
    /**
    * Constructs a new <code>Message</code>.
    * @alias module:model/Message
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Message} obj Optional instance to populate.
    * @return {module:model/Message} The populated <code>Message</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Message();

            
            
            

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('msgType')) {
                obj['msgType'] = ApiClient.convertToType(data['msgType'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('dateline')) {
                obj['dateline'] = ApiClient.convertToType(data['dateline'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} uid
    */
    uid = undefined;
    /**
    * @member {String} nickname
    */
    nickname = undefined;
    /**
    * @member {String} avatar
    */
    avatar = undefined;
    /**
    * @member {String} msgType
    */
    msgType = undefined;
    /**
    * @member {String} content
    */
    content = undefined;
    /**
    * @member {Date} dateline
    */
    dateline = undefined;








}


