/**
 * cookim
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Session from './Session';





/**
* The SessionList model module.
* @module model/SessionList
* @version 1.0.0
*/
export default class SessionList {
    /**
    * Constructs a new <code>SessionList</code>.
    * @alias module:model/SessionList
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SessionList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SessionList} obj Optional instance to populate.
    * @return {module:model/SessionList} The populated <code>SessionList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SessionList();

            
            
            

            if (data.hasOwnProperty('sessions')) {
                obj['sessions'] = ApiClient.convertToType(data['sessions'], [Session]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Session>} sessions
    */
    sessions = undefined;








}


