/**
 * cookim
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Session model module.
* @module model/Session
* @version 1.0.0
*/
export default class Session {
    /**
    * Constructs a new <code>Session</code>.
    * @alias module:model/Session
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Session</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Session} obj Optional instance to populate.
    * @return {module:model/Session} The populated <code>Session</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Session();

            
            
            

            if (data.hasOwnProperty('sessionid')) {
                obj['sessionid'] = ApiClient.convertToType(data['sessionid'], 'String');
            }
            if (data.hasOwnProperty('createuid')) {
                obj['createuid'] = ApiClient.convertToType(data['createuid'], 'String');
            }
            if (data.hasOwnProperty('ouid')) {
                obj['ouid'] = ApiClient.convertToType(data['ouid'], 'String');
            }
            if (data.hasOwnProperty('sessionName')) {
                obj['sessionName'] = ApiClient.convertToType(data['sessionName'], 'String');
            }
            if (data.hasOwnProperty('sessionType')) {
                obj['sessionType'] = ApiClient.convertToType(data['sessionType'], 'Number');
            }
            if (data.hasOwnProperty('sessionIcon')) {
                obj['sessionIcon'] = ApiClient.convertToType(data['sessionIcon'], 'String');
            }
            if (data.hasOwnProperty('publicType')) {
                obj['publicType'] = ApiClient.convertToType(data['publicType'], 'Number');
            }
            if (data.hasOwnProperty('lastUpdate')) {
                obj['lastUpdate'] = ApiClient.convertToType(data['lastUpdate'], 'Date');
            }
            if (data.hasOwnProperty('dateline')) {
                obj['dateline'] = ApiClient.convertToType(data['dateline'], 'Date');
            }
            if (data.hasOwnProperty('newCount')) {
                obj['newCount'] = ApiClient.convertToType(data['newCount'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} sessionid
    */
    sessionid = undefined;
    /**
    * @member {String} createuid
    */
    createuid = undefined;
    /**
    * @member {String} ouid
    */
    ouid = undefined;
    /**
    * @member {String} sessionName
    */
    sessionName = undefined;
    /**
    * @member {Number} sessionType
    */
    sessionType = undefined;
    /**
    * @member {String} sessionIcon
    */
    sessionIcon = undefined;
    /**
    * @member {Number} publicType
    */
    publicType = undefined;
    /**
    * @member {Date} lastUpdate
    */
    lastUpdate = undefined;
    /**
    * @member {Date} dateline
    */
    dateline = undefined;
    /**
    * @member {Number} newCount
    */
    newCount = undefined;
    /**
    * @member {Object} message
    */
    message = undefined;








}


