/**
 * cookim
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SessionList from '../model/SessionList';

/**
* ListSessions service.
* @module api/ListSessionsApi
* @version 1.0.0
*/
export default class ListSessionsApi {

    /**
    * Constructs a new ListSessionsApi. 
    * @alias module:api/ListSessionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * get content
     * @param {module:model/String} isPublicOrPrivate the indicator of whether it is public or private
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SessionList} and HTTP response
     */
    listSessionsWithHttpInfo(isPublicOrPrivate) {
      let postBody = null;

      // verify the required parameter 'isPublicOrPrivate' is set
      if (isPublicOrPrivate === undefined || isPublicOrPrivate === null) {
        throw new Error("Missing the required parameter 'isPublicOrPrivate' when calling listSessions");
      }


      let pathParams = {
        'isPublicOrPrivate': isPublicOrPrivate
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basic', 'oauth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SessionList;

      return this.apiClient.callApi(
        '/{isPublicOrPrivate}/listSessions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * get content
     * @param {module:model/String} isPublicOrPrivate the indicator of whether it is public or private
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SessionList}
     */
    listSessions(isPublicOrPrivate) {
      return this.listSessionsWithHttpInfo(isPublicOrPrivate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
