/**
 * cookim
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CookIM);
  }
}(this, function(expect, CookIM) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CookIM.Session();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Session', function() {
    it('should create an instance of Session', function() {
      // uncomment below and update the code to test Session
      //var instane = new CookIM.Session();
      //expect(instance).to.be.a(CookIM.Session);
    });

    it('should have the property sessionid (base name: "sessionid")', function() {
      // uncomment below and update the code to test the property sessionid
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property createuid (base name: "createuid")', function() {
      // uncomment below and update the code to test the property createuid
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property ouid (base name: "ouid")', function() {
      // uncomment below and update the code to test the property ouid
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property sessionName (base name: "sessionName")', function() {
      // uncomment below and update the code to test the property sessionName
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property sessionType (base name: "sessionType")', function() {
      // uncomment below and update the code to test the property sessionType
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property sessionIcon (base name: "sessionIcon")', function() {
      // uncomment below and update the code to test the property sessionIcon
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property publicType (base name: "publicType")', function() {
      // uncomment below and update the code to test the property publicType
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdate (base name: "lastUpdate")', function() {
      // uncomment below and update the code to test the property lastUpdate
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property dateline (base name: "dateline")', function() {
      // uncomment below and update the code to test the property dateline
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property newCount (base name: "newCount")', function() {
      // uncomment below and update the code to test the property newCount
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new CookIM.Session();
      //expect(instance).to.be();
    });

  });

}));
