swagger: '2.0'
info:
  title: cookim
  version: 1.0.0
host: 127.0.0.1:8080
schemes:
  - http
basePath: /api/v2
produces:
  - application/json
security:
  - basic: []
  - oauth: []
securityDefinitions:
  basic:
    type: basic
    flow: password
  oauth:
    type: oauth2
    flow: password
paths:
  /ping:
    get:
      summary: ping api server
      operationId: pingPong
      tags:
        - pingPong
      responses:
        200:
          description: returns pong
          schema:
              $ref: '#/definitions/PingPong'
  /login:
    get:
      summary: login server
      operationId: login
      tags:
        - login
      responses:
        200:
          description: returns token
          schema:
              $ref: '#/definitions/LoginResult'
  /{isPublicOrPrivate}/listSessions:
    get:
      summary: get content
      parameters:
        - name: isPublicOrPrivate
          description: the indicator of whether it is public or private
          in: path
          type: string
          enum:
            - public
            - private
          required: true
      operationId: listSessions
      tags:
        - listSessions
      responses:
        200:
          description: returns content
          schema:
              $ref: '#/definitions/SessionList'
definitions:
  PingPong:
    type: object
    properties:
      result:
        type: string
  LoginResult:
    type: object
    properties:
      login:
        type: string
      uid:
        type: string
      userToken:
        type: string
      msg:
        type: string
  SessionList:
    type: object
    properties:
      sessions:
        type: array
        items:
          $ref: '#/definitions/Session'
  Session:
    type: object
    properties:
      sessionid:
        type: string
      createuid:
        type: string
      ouid:
        type: string
      sessionName:
        type: string
      sessionType:
        type: integer
        format: int32
      sessionIcon:
        type: string
      publicType:
        type: integer
        format: int32
      lastUpdate:
        type: string
        format: date-time
        x-chance-type: date
      dateline:
        type: string
        format: date-time
        x-chance-type: date
      newCount:
        type: integer
        format: int32
      message:
        type: object
        items:
          $ref: '#/definitions/Message'
  Message:
    type: object
    properties:
      uid:
        type: string
      nickname:
        type: string
      avatar:
        type: string
      msgType:
        type: string
      content:
        type: string
      dateline:
        type: string
        format: date-time
        x-chance-type: date